### ISSUE TITLE
"Strange" Behaviour

### ISSUE THREAD

**Issue by JEuler** [typst/hypher#5]
I'm very new for Rust and I am working on small projects to learn it. So, I have the following code to count the syllables:
```rust
s.split_whitespace().for_each(|word| {
                let syllables = hyphenate(word, Lang::English);
                println!("{:?} has {} syllables", word, syllables.clone().count());
                count += syllables.count();
            });
```
where s is the just &str. So, I am splitting the thing to words and call `hyphenate` on each word. But I get the following output:
```
"An"
"An" has 1 syllables
Syllables { word: "An", cursor: 0, levels: [0] }
"old"
"old" has 1 syllables
Syllables { word: "old", cursor: 0, levels: [0, 0] }
"silent"
"silent" has 1 syllables
Syllables { word: "silent", cursor: 0, levels: [0, 2, 4, 0, 0] }
"pond"
"pond" has 1 syllables
Syllables { word: "pond", cursor: 0, levels: [0, 0, 0] }
```

So, is that something I don't get about how I should call the function? I've tried the example and it worked correctly. 
Sorry and thank you!

**Comment by laurmaedje** [comment]
The hyphenation patterns aren't perfect and `silent` seems to yield wrong results. You are using the crate correctly.

**Comment by JEuler** [comment]
Can I help somehow? :)

**Comment by laurmaedje** [comment]
I don't think there's much we can do here, since the hyphenation patterns are just taken from TeX. Many hyphenation engines use these patterns, which is also why you can observe the same problem here: https://www.hyphenation24.com/word/silent/

**Comment by Enivex** [comment]
I think syllables may be a misnomer?

Hyphenation boundaries do not always coincide with syllables. There can be other reasons for why hyphenation isn't desirable (like ambiguity). Also, the number of syllables can even depend on dialect.

In this case babel (which uses the same hyphenation patterns) yields
![image](https://github.com/typst/hypher/assets/2191754/19d8589f-d960-4923-8434-44d2368ccc91)
for US english, but
![image](https://github.com/typst/hypher/assets/2191754/cc936ed5-4ad1-4eaa-baa7-aa4de2bd4e8c)
for UK english (the line indicates a hyphenation boundary.

I think this is intentional.

**Comment by Enivex** [comment]
I just noticed that hypher seems to only have US english and not UK english though.
